# Generated by Django 5.0.2 on 2024-02-23 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='createdate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updatedate',
        ),
    ]
